## Project Description: Next Word Prediction Using LSTM
#### Project Overview:

This project aims to develop a deep learning model for predicting the next word in a given sequence of words. The model is built using Long Short-Term Memory (LSTM) networks, which are well-suited for sequence prediction tasks. The project includes the following steps:

1- Data Collection: We use the text of Shakespeare's "Hamlet" as our dataset. This rich, complex text provides a good challenge for our model.

2- Data Preprocessing: The text data is tokenized, converted into sequences, and padded to ensure uniform input lengths. The sequences are then split into training and testing sets.

3- Model Building: An LSTM model is constructed with an embedding layer, two LSTM layers, and a dense output layer with a softmax activation function to predict the probability of the next word.

4- Model Training: The model is trained using the prepared sequences, with early stopping implemented to prevent overfitting. Early stopping monitors the validation loss and stops training when the loss stops improving.

5- Model Evaluation: The model is evaluated using a set of example sentences to test its ability to predict the next word accurately.

6- Deployment: A Streamlit web application is developed to allow users to input a sequence of words and get the predicted next word in real-time.

In [1]:
## Data Collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import  pandas as pd

## load the dataset
data=gutenberg.raw('shakespeare-caesar.txt')
## save to a file
with open('caesar.txt','w') as file:
    file.write(data)

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [2]:
## Data Preprocessing

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

##laod the dataset
with open('caesar.txt','r') as file:
    text=file.read().lower()

## Tokenize the text-creating indexes for words
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1
total_words



3086

In [8]:
tokenizer.word_index

{'and': 1,
 'the': 2,
 'i': 3,
 'to': 4,
 'you': 5,
 'of': 6,
 'that': 7,
 'a': 8,
 'not': 9,
 'is': 10,
 'in': 11,
 'my': 12,
 'it': 13,
 'caesar': 14,
 'me': 15,
 'he': 16,
 'for': 17,
 'this': 18,
 'him': 19,
 'will': 20,
 'brutus': 21,
 'his': 22,
 'bru': 23,
 'with': 24,
 'your': 25,
 'be': 26,
 'haue': 27,
 'but': 28,
 'so': 29,
 'as': 30,
 'what': 31,
 'shall': 32,
 'do': 33,
 'thou': 34,
 'are': 35,
 'all': 36,
 'then': 37,
 'cassi': 38,
 'by': 39,
 'we': 40,
 'no': 41,
 'our': 42,
 'cassius': 43,
 'if': 44,
 'on': 45,
 'antony': 46,
 'come': 47,
 'did': 48,
 'good': 49,
 'men': 50,
 'o': 51,
 'know': 52,
 'when': 53,
 'they': 54,
 'was': 55,
 'enter': 56,
 'let': 57,
 'now': 58,
 'vs': 59,
 'their': 60,
 'them': 61,
 'man': 62,
 'at': 63,
 'am': 64,
 'thy': 65,
 'heere': 66,
 'thee': 67,
 'from': 68,
 'there': 69,
 'ant': 70,
 'well': 71,
 'vpon': 72,
 'which': 73,
 'day': 74,
 'would': 75,
 'lord': 76,
 'or': 77,
 'why': 78,
 'yet': 79,
 'night': 80,
 'go': 81,
 'some': 82,
 

In [9]:
## create inoput sequences
input_sequences=[]
for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_sequences.append(n_gram_sequence)

        

In [10]:
input_sequences

[[2, 896],
 [2, 896, 6],
 [2, 896, 6, 1381],
 [2, 896, 6, 1381, 14],
 [2, 896, 6, 1381, 14, 39],
 [2, 896, 6, 1381, 14, 39, 1382],
 [2, 896, 6, 1381, 14, 39, 1382, 1383],
 [2, 896, 6, 1381, 14, 39, 1382, 1383, 1384],
 [476, 1385],
 [476, 1385, 1386],
 [476, 1385, 1386, 1387],
 [56, 477],
 [56, 477, 897],
 [56, 477, 897, 1],
 [56, 477, 897, 1, 400],
 [56, 477, 897, 1, 400, 898],
 [56, 477, 897, 1, 400, 898, 301],
 [56, 477, 897, 1, 400, 898, 301, 2],
 [56, 477, 897, 1, 400, 898, 301, 2, 1388],
 [477, 235],
 [477, 235, 236],
 [477, 235, 236, 5],
 [477, 235, 236, 5, 700],
 [477, 235, 236, 5, 700, 899],
 [477, 235, 236, 5, 700, 899, 253],
 [477, 235, 236, 5, 700, 899, 253, 5],
 [477, 235, 236, 5, 700, 899, 253, 5, 236],
 [10, 18],
 [10, 18, 8],
 [10, 18, 8, 1389],
 [10, 18, 8, 1389, 31],
 [10, 18, 8, 1389, 31, 52],
 [10, 18, 8, 1389, 31, 52, 5],
 [10, 18, 8, 1389, 31, 52, 5, 9],
 [274, 1390],
 [274, 1390, 5],
 [274, 1390, 5, 558],
 [274, 1390, 5, 558, 9],
 [274, 1390, 5, 558, 9, 362],
 [72

In [11]:
## Pad Sequences
max_sequence_len=max([len(x) for x in input_sequences])
max_sequence_len

14

In [12]:
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,    2,  896],
       [   0,    0,    0, ...,    2,  896,    6],
       [   0,    0,    0, ...,  896,    6, 1381],
       ...,
       [   0,    0,    0, ...,    2,  896,    6],
       [   0,    0,    0, ...,  896,    6, 3085],
       [   0,    0,    0, ...,    6, 3085,   14]])

In [13]:
##create predicitors and label
import tensorflow as tf
x,y=input_sequences[:,:-1],input_sequences[:,-1]

In [14]:
x

array([[   0,    0,    0, ...,    0,    0,    2],
       [   0,    0,    0, ...,    0,    2,  896],
       [   0,    0,    0, ...,    2,  896,    6],
       ...,
       [   0,    0,    0, ..., 3084,    2,  896],
       [   0,    0,    0, ...,    2,  896,    6],
       [   0,    0,    0, ...,  896,    6, 3085]])

In [15]:
y

array([ 896,    6, 1381, ...,    6, 3085,   14])

In [16]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [17]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [18]:
# Define early stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

In [19]:
## Train our LSTM RNN

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,GRU

## Define the model
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation="softmax"))

# #Compile the model
model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 13, 100)           308600    
                                                                 
 lstm (LSTM)                 (None, 13, 150)           150600    
                                                                 
 dropout (Dropout)           (None, 13, 150)           0         
                                                                 
 lstm_1 (LSTM)               (None, 100)               100400    
                                                                 
 dense (Dense)               (None, 3086)              311686    
                                                                 
Total params: 871286 (3.32 MB)
Trainable params: 871286 (3.32 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
## GRU RNN
## Define the model
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(GRU(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(GRU(100))
model.add(Dense(total_words,activation="softmax"))

# #Compile the model
model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 13, 100)           308600    
                                                                 
 gru (GRU)                   (None, 13, 150)           113400    
                                                                 
 dropout_1 (Dropout)         (None, 13, 150)           0         
                                                                 
 gru_1 (GRU)                 (None, 100)               75600     
                                                                 
 dense_1 (Dense)             (None, 3086)              311686    
                                                                 
Total params: 809286 (3.09 MB)
Trainable params: 809286 (3.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
## Train the model
history=model.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test),verbose=1,callbacks=[early_stopping])


Epoch 1/50
444/444 [==============================] - 34s 57ms/step - loss: 6.7867 - accuracy: 0.0259 - val_loss: 6.6996 - val_accuracy: 0.0265
Epoch 2/50
444/444 [==============================] - 22s 50ms/step - loss: 6.4033 - accuracy: 0.0270 - val_loss: 6.6413 - val_accuracy: 0.0265
Epoch 3/50
444/444 [==============================] - 21s 48ms/step - loss: 6.2575 - accuracy: 0.0285 - val_loss: 6.6503 - val_accuracy: 0.0335
Epoch 4/50
444/444 [==============================] - 21s 46ms/step - loss: 6.1117 - accuracy: 0.0386 - val_loss: 6.6152 - val_accuracy: 0.0436
Epoch 5/50
444/444 [==============================] - 20s 45ms/step - loss: 5.9492 - accuracy: 0.0526 - val_loss: 6.5686 - val_accuracy: 0.0552
Epoch 6/50
444/444 [==============================] - 21s 47ms/step - loss: 5.7328 - accuracy: 0.0663 - val_loss: 6.5844 - val_accuracy: 0.0619
Epoch 7/50
444/444 [==============================] - 20s 45ms/step - loss: 5.5015 - accuracy: 0.0812 - val_loss: 6.5989 - val_accuracy:

In [22]:
# Function to predict the next word
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len-1):]  # Ensure the sequence length matches max_sequence_len-1
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None

In [23]:
input_text="To be or not to be"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:To be or not to be
Next Word PRediction:thing


In [26]:
## Save the model
model.save("next_word_lstm.h5")
## Save the tokenizer
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

OSError: [Errno 22] Unable to create file (unable to open file: name = 'next_word_lstm.h5', errno = 22, error message = 'Invalid argument', flags = 13, o_flags = 302)

In [27]:
input_text="  Barn. Last night of all,When yond same"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:  Barn. Last night of all,When yond same
Next Word PRediction:cosin
